### ISSUE TITLE
cant save HTML templates and no analytics section

### ISSUE THREAD

**Issue by SantaHub** [freeCodeCamp/mail-for-good#269] opened 2018-02-10 05:07 UTC
<img width="1920" alt="screen shot 2018-02-10 at 10 32 41 am" src="https://user-images.githubusercontent.com/12994795/36058726-43294cf6-0e4e-11e8-814c-47416b9aa4d4.png">

Followed Mail for good documentation. Did i miss anything ? I cant get the analytic tab and couldnt save HTML templates.

**Comment by zhakkarn** [comment] 2018-02-13 03:58
Hi @SantaHub , Could you please give me more details about what you are expecting to find? 
The analytics are on the "campaign>manage campaign" tab and on the dashboard. As to the HTML template, I just saved a brand new one and sent it to myself without encountering any problems so I'll need the exact steps you used to recreate the problem.

**Comment by zhakkarn** [comment] 2018-02-21 01:48
Can't reproduce and no bump/details from author. Closing for now.

**Closed by zhakkarn** 2018-02-21 01:48 UTC
Labels: problem/bug
