### ISSUE TITLE
How to paste html code?

### ISSUE THREAD

**Issue by Rigel772** [freeCodeCamp/mail-for-good#224] opened 2017-10-09 10:41 UTC
Is it possible to send html email without using the html WYSIWYG editor? Just to paste html code?
Thanks :)

**Comment by karuppiah7890** [comment] 2017-10-09 13:54
I am actually able to paste plain html code in my editor. You are not able to ?

**Comment by Rigel772** [comment] 2017-10-09 15:24
I can but I am seeing html code, not converted... Can you show me a sample of what do you paste in? Is the css inline?

**Comment by Rigel772** [comment] 2017-10-09 15:53
Actually as I try now you can select "txt message", paste html and then switch to "html message" when the code gets converted... but html styling is very limited... :(

**Comment by karuppiah7890** [comment] 2017-10-09 16:02
Okay, I am sorry I didn't know about HTML templates properly. There are already issues regarding this. #100 #115 You can't actually paste raw HTML and expect it to render. If you paste raw HTML, I believe it will escaped and it will be seen raw in the mail and not rendered. But there's a rich text editor to create basic HTML template for now.

**Comment by karuppiah7890** [comment] 2017-10-09 16:04
And about pasting HTML in text template and changing to HTML template, it does work in a basic manner. I tried it out. But I have to check if styles work too

**Comment by karuppiah7890** [comment] 2017-10-09 16:08
And the styling is probably limited because it's just like a rich text editor, not a complete HTML template editor so, when you switch between text and HTML templates, the maximum styling you can have is what a rich text editor can have

**Comment by karuppiah7890** [comment] 2017-10-09 16:09
duplicate #100

**Comment by Rigel772** [comment] 2017-10-10 04:47
thanks for the information, I believe being able to send html email is essential feature... I mean proper html
You do not need to render the code in the app - I would not care for the preview if the code was sent and rendered properly on receiver end.
It is a shame you cannot bypass somehow the rich text editor... :(

**Comment by karuppiah7890** [comment] 2017-10-10 13:28
Thing is, many non-profit organizations want text only templates - plain text or HTML containing styled text (rich text). We will be supporting HTML only in the later versions I believe

**Comment by karuppiah7890** [comment] 2017-10-10 13:29
And no, I don't have any list of HTML tags that work. I think - only the rich text editor compatible elements will work, so it's better to just use the rich text editor than type it all

**Comment by Rigel772** [comment] 2017-10-10 14:09
There is unordered list styling in rich text editor but emails are delivered without these tags...

**Comment by karuppiah7890** [comment] 2017-10-10 14:39
? I don't get you, what tags ?

**Comment by Rigel772** [comment] 2017-10-10 14:50
On second test the <li> look ok, not sure what happened before, sorry for false alarm :)

**Comment by karuppiah7890** [comment] 2017-10-10 15:08
Okay! And I am gonna close this issue as it's a duplicate of #100 #115

**Closed by karuppiah7890** 2017-10-10 15:08 UTC
Labels: feedback/question
