### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by r-kommerce** [freeCodeCamp/mail-for-good#265] opened 2018-01-16 11:03 UTC
Followed instructions from https://github.com/freeCodeCamp/mail-for-good/blob/master/docs/aws_deploy.md

Server is up, docker is running, when hitting the website, prompted for google login.  Have tried with different credentials but the end result is the same:

Internal Server Error

Looking at docker-compose logs output:

app_1       | Error
app_1       |     at /usr/src/app/node_modules/passport-google-oauth20/lib/strategy.js:95:21
app_1       |     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth2.js:132:9)
app_1       |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:157:7)
app_1       |     at emitNone (events.js:110:20)
app_1       |     at IncomingMessage.emit (events.js:207:7)
app_1       |     at endReadableNT (_stream_readable.js:1045:12)
app_1       |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
app_1       |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

Not sure if this is helpful in debugging the issue.  There are some gaps in the documentation for the google api portion (such as having to create a project) and there are multiple options for Google+ when enabling APIs.  Otherwise we faithfully followed the provided instructions (and two different people ran through them, with the same end result).

Happy to work with you to see why this doesn't seem to run out of the box.

**Comment by zhakkarn** [comment] 2018-01-16 19:30
The credentials you need are on a page looking like [this](https://imgur.com/YmYKKJi). The same page in which you specified the post-authentication redirect. Can you confirm me that these are the ones you are using?

Unfortunately, the logs you are providing are telling me that you had an authentication problem. Nothing more.

**Comment by r-kommerce** [comment] 2018-01-17 06:13
I can confirm that I am using the credentials from that page.  If there is any way to provide additional debugging information please let me know. 
![putty-cred](https://user-images.githubusercontent.com/35488764/35028328-87307472-fb90-11e7-9c13-14ade36119c7.PNG)
![web-cred](https://user-images.githubusercontent.com/35488764/35028329-87613378-fb90-11e7-9832-586c4a9a1bd6.PNG)

**Comment by zhakkarn** [comment] 2018-01-17 16:37
With the current feedback we are getting I've started to rework the process of deploying MfG. The current strategy is too heavy resulting in a forever-unsufficient documentation and inconsistent success rate. For some it works out of the box, for some, it's on their 2nd try with apparently no differences from the 1st attempt and in some other cases the authentication is a problem which has a different solution every time.

Unless your deployment is urgent in which case I'll do my best to assist you. I'll focus on compressing the process of deploying instances of MfG as close as "one-click installation" as I can and then notify you.

Regardless, thank you for taking on your time to give us a try in our beta phase.

**Comment by r-kommerce** [comment] 2018-01-22 04:28
We appreciate your generosity in offering to help us get this set up. While our need is somewhat urgent, I prefer that you use your valuable time to improve/bullet-proof MfG to amplify the benefit to the community, especially seeing as this is a problem that has/will hit other people.  We look forward to trying it again when you've had a chance to further refine the installation process!

**Comment by edgardok** [comment] 2018-01-24 15:24
hi!  im in the same problem, looking for a solution:

app_1       | 
app_1       |   ############################
app_1       |   #   Mail 4 Good started    #
app_1       |   ############################
app_1       |   # Port: 8080
app_1       |   ############################
app_1       |   
app_1       | (node:47) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
app_1       | Error
app_1       |     at /usr/src/app/node_modules/passport-google-oauth20/lib/strategy.js:95:21
app_1       |     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth2.js:132:9)
app_1       |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:157:7)
app_1       |     at emitNone (events.js:110:20)
app_1       |     at IncomingMessage.emit (events.js:207:7)
app_1       |     at endReadableNT (_stream_readable.js:1045:12)
app_1       |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
app_1       |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by zhakkarn** [comment] 2018-01-26 23:51
@r-kommerce  and @edgardok . I forgot about this possibility : did you enable the [google+ API](https://imgur.com/7kRWpa4)?

**Comment by ohansemmanuel** [comment] 2018-03-03 17:24
@zhakkarn thanks for your input here. I seem to be having the same issue. is there an imminent fix around the corner? 

Thank you!

**Comment by zhakkarn** [comment] 2018-03-03 21:56
@ohansemmanuel , next week (Wednesday?) authenticating using Google+ will be opt-in and the default way to login will be through the classic email/password process. This will remove the need to set up your access to the Google+ api from your instance and by consequence, it will fix this problem and remove some hassle from the setup.

**Comment by ohansemmanuel** [comment] 2018-03-06 02:54
Thanks a lot! @zhakkarn

**Comment by zlfdtc1983** [comment] 2018-05-07 04:55
I have the same problem.  I have enabled Google+ API, but error still happens.

**Comment by zhakkarn** [comment] 2018-05-28 18:03
Due to a lack of information and an impossibility to reproduces the bugs I'll go ahead on close this.

**Closed by zhakkarn** 2018-05-28 18:03 UTC

**Comment by smakintel** [comment] 2019-08-22 05:23
Guys I encountered the same issue, enabled google + API in Project (google) fixed this for me
