### ISSUE TITLE
socket.io-client npm module missing in package.json file

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#167] opened 2017-07-16 07:26 UTC
When I executed the `dev` script's command, I got an error for webpack building, and it said that it wasn't able to resolve `socket.io-client`, as in not able to find the module

Log : 
```
karuppiah@karuppiah ~/F/Mail-for-Good> export DEV_SEND_RATE=200; export NODE_ENV=development; node server/index.js
Clickthrough tracking: Make sure that geoip data has been downloaded: 
   $ cd node_modules/geoip-lite
   $ npm run-script updatedb

  ############################
  #   Mail 4 Good started    #
  ############################
  # Port: 8080
  ############################
  
(node:25835) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
webpack: wait until bundle finished: /index.html
webpack built 826606c0bc2c15cbc98f in 42897ms

ERROR in ./client/actions/appActions.js
Module not found: Error: Can't resolve 'socket.io-client' in '/home/karuppiah/FOSS/Mail-for-Good/client/actions'
 @ ./client/actions/appActions.js 13:14-41
 @ ./client/containers/App.js
 @ ./client/routes.js
 @ ./client/index.js
 @ multi ./client/webpack-public-path react-hot-loader/patch webpack-hot-middleware/client?reload=true ./client/index.js
webpack: Failed to compile.
^C⏎                                                                                                                                                                                       
```

**Comment by AndrewGHC** [comment] 2017-07-16 10:39
Seems this issue was reported here, but I can't reproduce it https://github.com/socketio/socket.io/issues/2801

However we're using the right syntax as below and I'm not able to reproduce it. I will have another look shortly.

https://github.com/socketio/socket.io/blob/master/examples/webpack-build/lib/index.js

**Comment by karuppiah7890** [comment] 2017-07-16 10:53
@AndrewGHC Everything works fine if we install the npm module and save it in the `package.json` too, and in the above examples also, I see that the module is installed and saved in the `package.json`
 file here : https://github.com/socketio/socket.io/blob/master/examples/webpack-build/package.json

I think it works for you because it's installed, just not present in your `package.json` may be ? Try a clean `npm install` after removing `node_modules` folder and you should be able to see that `socket.io-client` module is not installed and this error pops up in the console. And the issue you mentioned, the comments there say that it has to be imported in a different manner by digging into `socket.io` module's `node_modules` folder, or we can just use the separate [`socket.io-client`](https://github.com/socketio/socket.io-client) that I just mentioned in this issue

**Comment by karuppiah7890** [comment] 2017-07-16 18:08
Looks like there are a lot of issues with npm. I am not able to run the current version with `npm-run-all` not found, and the module is not present in the node_modules folder. Same for `webpack`. This happened after I tried a clean `npm install`. The development dependencies weren't installed properly. Some weird behavior

**Comment by AndrewGHC** [comment] 2017-07-16 22:05
I was not able to reproduce this:

Node = 8.1.4
NPM = 5.0.3

Steps:
Cloned the repo
Copied over a working .env file
Npm install
Nom build
Npm start

**Comment by karuppiah7890** [comment] 2017-07-17 06:28
@AndrewGHC Ah. Looks like I shouldn't update npm to the latest version always. Gotta find the stable ones. I am using `5.3.0` after `5.2.0` wasn't helping

**Comment by karuppiah7890** [comment] 2017-07-19 12:09
@AndrewGHC I think we should just stick to npm `v5.0.3` and check things or find some other version which is stable and test things, because now it works for me. Even #166 bug doesn't pop up

**Comment by AndrewGHC** [comment] 2017-07-28 22:03
I'm going to close this one as if this issue is related to the NPM problems discussed elsewhere. The socket.io-client package is not itself missing, as it is part of the socket.io library. This issue emerged when the package was incorrectly handled by NPM, causing it to skip the package in question.

It might be that we need to ensure that we use an NPM version that has addressed this issue. As part of the move towards Dockerising everything, we'll be able to control this factor.

**Closed by AndrewGHC** 2017-07-28 22:03 UTC
